# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Server
host:             0.0.0.0
port:             9001
baseurl:          /
url:              http://localhost:9001
encoding:         UTF-8

# the excluded directoies
exclude:
  - "conf"
  - "tools"

# site information
info:
  site_name:    Bt-docs

meta:
  description:  Write beautiful bootstrap style document in an easy way.
  keywords:     bootstrap documentation template, beautiful documentation, bootstrap template
  author:       liaohuqiu@gmail.com

#multiple language
language_default: 'en'

languages:      ["en", "cn"]

navigation:
  en:
    title:          Bt-docs
    path:           /
    items:          []
  cn:
    title:          Bt-docs
    path:           /cn
    items:          []

right_nav:
  - title:    English Version
    url:      /
  - title:    中文版文档
    url:      /cn
  - title:    Fork on Github
    url:     https://github.com/liaohuqiu/bt-docs

# analytics account info
analytics:
  google:
    account:    UA-43024238-3

# other informations about this project
download:
  rep:          https://github.com/liaohuqiu/bt-docs
  dist:         https://github.com/liaohuqiu/bt-docs/archive/master.zip
